trigger:
  branches:
    include:
      - Test-1

variables:
  - group: Access for git

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: PowerShell@2
  displayName: 'Install Power BI PowerShell Modules'
  inputs:
    targetType: 'inline'
    script: |
      Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser -AllowClobber

- task: PowerShell@2
  displayName: 'Deploy PBIX to Power BI Workspace'
  inputs:
    targetType: 'inline'
    script: |
      $ErrorActionPreference = "Stop"

      $tenantId = "$(TENANT_ID)"
      $clientId = "$(CLIENT_ID)"
      $clientSecret = "$(CLIENT_SECRET)"
      $workspaceName = "$(WORKSPACE_NAME)"
      $pbixPath = "$(Build.SourcesDirectory)\Report.pbix"  # Update if file is in subfolder
      $datasetName = "Healthcare Report"

      # Authenticate with Service Principal
      $securePassword = ConvertTo-SecureString $clientSecret -AsPlainText -Force
      $credential = New-Object System.Management.Automation.PSCredential($clientId, $securePassword)

      Connect-PowerBIServiceAccount -ServicePrincipal -Credential $credential -Tenant $tenantId

      # Get Workspace
      $workspace = Get-PowerBIWorkspace -Name $workspaceName
      if (-not $workspace) {
          throw "Workspace '$workspaceName' not found."
      }

      # Import PBIX
      Import-PowerBIReport -Path $pbixPath -WorkspaceId $workspace.Id -Name $datasetName -ConflictAction CreateOrOverwrite
