trigger:
  branches:
    include:
      - Test-1

pool:
  vmImage: 'windows-latest'

variables:
  PBI_TENANT_ID: 'b8b38bb6-d128-4ce2-bc75-832204613f0d'
  PBI_CLIENT_ID: 'efb69f03-2d77-4386-a4db-0c7165e80ee2'
  PBI_WORKSPACE_ID_TEST: '8cadcdf4-a1be-4734-bd6e-1164f919d502'
  PBIX_PATH: 'MDJ DASHBOARD.pbix'  # 🟢 File name exactly as in your GitHub repo

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: PowerShell@2
  displayName: 'Install Power BI Modules'
  inputs:
    targetType: 'inline'
    script: |
      Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser
      Install-Module -Name MicrosoftPowerBIMgmt.Profile -Force -Scope CurrentUser

- task: PowerShell@2
  displayName: 'Deploy PBIX to Power BI Test Workspace'
  inputs:
    targetType: 'inline'
    script: |
      $tenantId = "$(PBI_TENANT_ID)"
      $clientId = "$(PBI_CLIENT_ID)"
      $workspaceId = "$(PBI_WORKSPACE_ID_TEST)"
      $clientSecret = "$(PBI_CLIENT_SECRET)"  # ❗ Set this in pipeline variables as a secret
      $pbixPath = "$(PBIX_PATH)"

      $secureSecret = ConvertTo-SecureString $clientSecret -AsPlainText -Force
      $credential = New-Object System.Management.Automation.PSCredential($clientId, $secureSecret)

      Connect-PowerBIServiceAccount -ServicePrincipal -Credential $credential -TenantId $tenantId

      Write-Host "Uploading PBIX file..."
      New-PowerBIReport -Path $pbixPath -WorkspaceId $workspaceId -Name "MDJ Dashboard" -ConflictAction CreateOrOverwrite
