variables:
- group: PowerBISecrets  # This should be the name of your variable group

trigger:
  branches:
    include:
      - Test-1

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: 'Deploy PBIX to Power BI Workspace'
  inputs:
    targetType: 'inline'
    script: |
      # Print for debug
      Write-Host "Tenant: ${{ variables['PBI_TENANT_ID'] }}"
      Write-Host "Workspace ID: ${{ variables['PBI_WORKSPACE_ID_Test'] }}"

      # Assign from variables
      $tenantId = "${{ variables['PBI_TENANT_ID'] }}"
      $clientId = "${{ variables['PBI_CLIENT_ID'] }}"
      $clientSecret = "${{ variables['PBI_CLIENT_SECRET'] }}"
      $workspaceId = "${{ variables['PBI_WORKSPACE_ID_Test'] }}"  # <-- Test workspace
      $pbixPath = "$(Build.SourcesDirectory)\Report.pbix"
      $reportName = "Healthcare Report"

      # Authenticate
      $secureSecret = ConvertTo-SecureString $clientSecret -AsPlainText -Force
      $credential = New-Object System.Management.Automation.PSCredential($clientId, $secureSecret)
      Connect-PowerBIServiceAccount -ServicePrincipal -Credential $credential -TenantId $tenantId

      # Import report
      Import-P
